version: "3"

services:

  addresses_api:
    build: api/
    ports:
      - 8000:8000
    volumes:
      - ./api:/app

  streamlit_app:
    build: streamlit_app/
    ports:
      - 8501:8501
    volumes:
      - ./streamlit_app:/app